version: '3.8'

services:
  app:
    image: ghcr.io/ximeraproject/xake2024:latest # 
    # volumes:
    #   - .:/workspace:cached
    # command: /bin/sh -c "npm install && npm start"  # Customize command as needed
    # environment:
    #   - NODE_ENV=development
    # ports:
    #   - "3000:3000"  # Expose app's port (your Node.js app port)
  web:
    image: registry.gitlab.kuleuven.be/wet/ximera/ximeradocker:2.3.7j    # Using a specific Nginx image
    ports:
      - "2000:2000"          # Expose Nginx on port 8080
    # volumes:
    #   - ./nginx:/etc/nginx/conf.d  # Nginx configuration files or static files
    networks:
      - devnet             # Custom network for container communication
networks:
  devnet:
    driver: bridge
